### ISSUE TITLE
Build currently failing on master

### ISSUE THREAD

**Issue by Smaug123** [nickcowle/HCollections#8]
This is why we do pull requests, Nick :P
https://travis-ci.org/nickcowle/HCollections/builds/593963750

> Errors in /home/travis/build/nickcowle/HCollections/HCollections.Test/HCollections.Test.fsproj
1464    NU1605: Detected package downgrade: FSharp.Core from 4.6.2 to 4.5.2. Reference the package directly from the project to select a different version.
1465     HCollections.Test -> HCollections -> TypeEquality 0.2.3 -> FSharp.Core (>= 4.6.2)
1466     HCollections.Test -> FSharp.Core (>= 4.5.2)

**Comment by nickcowle** [comment]
Yes, apologies - I mistakenly believed that TypeEquality 0.2.3 only required FSharp.Core 4.5.0 (see https://github.com/G-Research/TypeEquality/pull/21/files), but it turns out that the package references were set up incorrectly and were being ignored. I fixed it here - https://github.com/G-Research/TypeEquality/pull/22 and have created TypeEquality 0.2.4 with the fix.

Fix to HCollections coming shortly in https://github.com/nickcowle/HCollections/pull/9.

**Comment by nickcowle** [comment]
Now fixed on master
